### ISSUE TITLE
Peer to Peer code Review

### ISSUE THREAD

**Issue by pinkmoon25** [principlebrothers/Portfolio-Mobile-Version#10]
First of all kudos to Ernest, he copied the design template very well and the page is well and responsive.

I think it would be better if we use the header links to jump to the appropriate section of the page, it improves accessibility on the page

I believe all the form elements are required and so you can use a _required_ attribute on the `textarea `element, it will improve the whole form section

**Comment by principlebrothers** [comment]
@PinkMoon25 Issue #10  has been resolved
